[package]
name = "nl80211-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
darling = "0.14.2"
syn = { version="1.0.107", features=["full"]}
quote ="1.0.23"